name: taxi_serving
version: "1.0.0"
config-version: 2

profile: taxi_serving

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  taxi_serving:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
