name: taxi_analytics
version: '1.0.0'
config-version: 2

profile: taxi_analytics

model-paths: ["models"]
macro-paths: ["macros"]
clean-targets: ["target", "dbt_packages"]

models:
  taxi_analytics:
    +materialized: table
